Feature/button component
mentai-pasta/auction-app pull request #48
Opened 2024-12-04 08:03 UTC by 96nekocake

ボタンコンポーネントを作成
## やったこと
ボタンコンポーネントの基礎となる部分を作った(足りないボタン多々あり）
## btn呼び出し
![391874039-fee920a7-1ca9-4064-bcc3-8da55f905eb6](https://github.com/user-attachments/assets/7f73be6d-5fe4-46ab-a510-c650cab26077)
## 呼び出されたボタンの表示例
<img width="328" alt="391873632-51eb9354-d819-41b5-b602-bebdfd994e26" src="https://github.com/user-attachments/assets/d37e430c-9888-4f29-8b51-2c0a1cdeaf53">

2024-12-04 08:05 UTC, 96nekocake commented
## ボタン追加
Typeに名前とlabelにボタンに表示したい文字を追加。
variantClassで色を指定
![carbon (1)](https://github.com/user-attachments/assets/c4da5023-64be-4e70-bb91-4607039b5d57)

2024-12-04 08:06 UTC, 96nekocake commented
tsあんまりわからんからこれであってるのか不安なのでレビューください @Alpha9n

2024-12-04 10:47 UTC, Alpha9n commented
画像にしてもらってるとこ悪いんやけどその辺コメントとかJSDoc使ってコードに書いておいて欲しい！！
レビューしづらいのと使う時にPR見に来るわけではないので！！

2024-12-05 02:18 UTC, 96nekocake commented
追記しときます！

2024-12-06 02:05 UTC, Alpha9n submitted a review, later dismissed
動くから一旦OK!!

2024-12-06 02:29 UTC, Alpha9n requested changes
配置ディレクトリをcomponents/atoms/Button.tsxにしてほしい！！

2024-12-06 03:13 UTC, 96nekocake commented
ディレクトリ変更してないのと、動作確認で転けたので作りかけです😭

2024-12-06 09:35 UTC, 96nekocake commented
色が変わらないので修正する

2024-12-06 14:41 UTC, 96nekocake commented
@Alpha9n レビューお願いします
<img src="https://media2.giphy.com/media/1Cdu8r25fJi3m/giphy.gif"/>

2024-12-06 14:52 UTC, Alpha9n approved these changes
LGTM!

2024-12-07 05:30 UTC, merged