add:alert component追加
mentai-pasta/auction-app pull request #53
Opened 2024-12-06 07:21 UTC by 96nekocake

# 新しい `Alert` コンポーネントの追加

このプルリクエストでは、新しい `Alert` コンポーネントを `apps/front/src/components/atoms/Alert.tsx` ファイルに追加しました。<br>
このコンポーネントは、daisyUIライブラリを使用してさまざまな種類のアラートを表示するために設計されています。

## 主な変更点

- **`Alert` コンポーネントの作成**  
  `alertType`、`label`、`buttonType`、`buttonLabel`、`buttonDisplay` のプロップを持つコンポーネントを作成し、カスタマイズ可能なアラートメッセージやボタンを提供。

- **デフォルトの `Alert` コンポーネントの実装**  
  オプションでボタンを表示可能なアラートを描画し、daisyUIのスタイルを活用して統一感のあるUIデザインを実現。

2024-12-06 07:22 UTC, 96nekocake commented
## bug
alert/buttonTypeを変更しても色が変わらない(一部変わる？)

2024-12-06 09:21 UTC, 96nekocake commented
対応完了

2024-12-06 09:30 UTC, 96nekocake commented
レビューお願いします

2024-12-06 13:35 UTC, Alpha9n commented
みます

2024-12-06 15:53 UTC, Alpha9n requested changes

2024-12-06 15:53 UTC, Alpha9n commented on apps/front/src/components/atoms/Alert.tsx
> +    btnDisplay = false,
```suggestion
    btnDisplay = false,
    onClick
```
アラート内のボタン押した時のonClickを外から呼び出せるようにしておいてほしい！！

2024-12-06 15:53 UTC, Alpha9n commented on apps/front/src/components/atoms/Alert.tsx
> +    btnDisplay?: boolean;
```suggestion
    btnDisplay?: boolean;
    onClick?: () => void;
```
アラート内のボタン押した時のonClickを外から呼び出せるようにしておいてほしい！！

2024-12-07 09:09 UTC, 96nekocake commented on apps/front/src/components/atoms/Alert.tsx
> +    btnDisplay = false,
レビューありがとう！追加しました🙏

2024-12-07 09:10 UTC, 96nekocake commented on apps/front/src/components/atoms/Alert.tsx
> +    btnDisplay?: boolean;
追加しました！

2024-12-07 09:11 UTC, Alpha9n approved these changes
LGTM!!!
![LGTM](https://looks-to.me/images/posts/buftwtofii4n20t3dff8uwgv)

2024-12-07 09:13 UTC, merged